ALTER TABLE USER_INFO ADD (NICKNAME VARCHAR(1024));

CREATE TABLE ENV
(
  ENV_NAME    VARCHAR(128)   NOT NULL,
  ENV_URL     VARCHAR(256)   NOT NULL,
  CREATE_USR  VARCHAR(128)   NOT NULL,
  CREATE_DT   DATETIME(6)    NOT NULL,
  MOD_DT      TIMESTAMP(6),
  MOD_USR     VARCHAR(128),
  PRIMARY KEY (ENV_NAME)
);

commit;

