# paths are relative to the location of this file
mdw:
  version: 6.1.39

asset:
  location: assets

config:
  location: config

data:
  workgroups:
    - Developers
    - MDW Support
  task:
    categories:
      Bug: ISSUE
      Documentation: DOCS
      General: GEN
      Comments: COM
      Test: TST
      Inventory: INV
      Planning: PLN
      Ordering: ORD
