schemaVersion: '6.1'
name: com.centurylink.mdw.system.filepanel
version: 6.1.36-SNAPSHOT

dependencies:
  - com.centurylink.mdw.base v6.1.36-SNAPSHOT
  - com.centurylink.mdw.node v6.1.36-SNAPSHOT
  - com.centurylink.mdw.react v6.1.36-SNAPSHOT
