schemaVersion: '6.1'
name: com.centurylink.mdw.system.filepanel
version: 6.1.39

dependencies:
  - com.centurylink.mdw.base v6.1.39
  - com.centurylink.mdw.node v6.1.39
  - com.centurylink.mdw.react v6.1.39
