schemaVersion: '6.1'
name: com.centurylink.mdw.milestones
version: 6.1.37

dependencies:
  - com.centurylink.mdw.base v6.1.37
  - com.centurylink.mdw.node v6.1.37
  - com.centurylink.mdw.react v6.1.37
