# If upstreamHosts is populated then access is restricted to this list
# unless running in dev mode (-Dmdw.runtime.env=dev).
upstreamHosts:
  - 127.0.0.1
  - 0:0:0:0:0:0:0:1
  
authMethod: mdw

# Allows access to all UI functions and Service APIs permitted for this
# user without authenticating.  Requires "-Dmdw.runtime.env=dev" system property.
devUser: mdwapp

# Auth exclusions are patterns that can be accessed directly
# without authentication even when running with protection 
# (upstreamHosts != null & not in dev mode). 
authExclusions:
  - '/login'
  - '/error'
  - '/js/nav.json'
  - '/customContent/js/nav.json'
  - '/images/*'
  - '/css/*'
  - '/api-docs/*'
  - '/services/demo/api/*'
  - '/services/AppSummary'
  - '/services/System/exit'
  - '/services/com/centurylink/mdw/slack'
  - '*.css'
  - '*.jsx'
  - '*.png'
  - '*.js'
  - '*.woff'
  - '*.woff2'
  - '*.ttf'
  
# Headers appended to all HTTP servlet responses.
responseHeaders:
  X-UA-Compatible: IE=Edge
  
# Session timeout in seconds (if not specified, container will govern).
sessionTimeout: 3600

# Allowing any authenticated user means even those not in mdw's db.
allowAnyAuthenticatedUser: false

# Special options for logging
loggingOptions:
  logResponseTimes: false
  logHeaders: false
  logParameters: false  