app:
  id: mdw-demo

servers:
  localhost:
    ports:
    - 8080

container:
  datasource.provider: Tomcat
  messenger: jms
  jms.provider: ActiveMQ
  threadpool.provider: MDW
  
database:
  driver: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3308/mdw
  username: mdw
  password: mdw
  poolsize: 10
  poolMaxIdle: 5
  validationQuery: select 1 from dual
  
asset:
  location: ./assets
  
git:
  local.path: .
  remote.url: https://github.com/CenturyLinkCloud/mdw-demo.git
  branch: master
  user: anonymous
  
temp.dir: ./temp

hub.url: http://localhost:8080/mdw
services.url: http://localhost:8080/mdw
central.url: https://mdw-central.com
discovery.url: http://repo.maven.apache.org/maven2

logging:
  level: DEBUG
  
filepanel:
  root.dirs:
    - ./deploy/logs
