application:
  name: mdw-demo

servers:
  localhost:
    ports:
    - 8080

container:
  datasource.provider: Tomcat
  messenger: jms
  jms.provider: ActiveMQ
  threadpool.provider: MDW
  
database:
  driver: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3308/mdw
  username: mdw
  password: mdw
  poolsize: 5
  poolMaxIdle: 3
  
asset:
  location: repo/assets
  
git:
  local.path: repo
  remote.url: https://github.com/CenturyLinkCloud/mdw-demo.git
  branch: master
  user: anonymous
  
temp.dir: ../.temp

hub.url: http://mdw-demo.mesosmasteridc01-test.idc1.level3.com:32100/mdw
services.url: http://mdw-demo.mesosmasteridc01-test.idc1.level3.com:32100/mdw

logging:
  level: DEBUG
