{
  "activities": [
    {
      "attributes": {"WORK_DISPLAY_INFO": "x=42,y=278,w=60,h=40"},
      "id": "A1",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
      "name": "Start",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=127,ly=295,xs=106&149,ys=295&295"},
        "event": "FINISH",
        "id": "T1",
        "to": "A3"
      }]
    },
    {
      "attributes": {
        "DoNotNotifyCaller": "false",
        "WORK_DISPLAY_INFO": "x=461,y=118,w=60,h=40"
      },
      "id": "A2",
      "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
      "name": "Stop"
    },
    {
      "attributes": {
        "Expression": "processCase",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=153,y=245,w=98,h=68"
      },
      "id": "A3",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptEvaluator",
      "name": "Which Case?",
      "transitions": [
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=202,ly=203,xs=202&202,ys=241&166"},
          "event": "FINISH",
          "id": "T2",
          "to": "A5"
        },
        {
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=385,ly=287,xs=255&516,ys=287&287"},
          "event": "FINISH",
          "id": "T3",
          "resultCode": "error handler delegation",
          "to": "A6"
        }
      ]
    },
    {
      "attributes": {
        "Rule": "$xmldata.MINUTES = \"2\";\r\n\r\n$intarraytest = \"1~1~2~3~5~8\";\r\n\r\n$maptest = \"R=red~G=green~B=blue\";\r\n\r\nsyntax error here",
        "SCRIPT": "Groovy",
        "WORK_DISPLAY_INFO": "x=136,y=103,w=133,h=59"
      },
      "id": "A5",
      "implementor": "com.centurylink.mdw.workflow.activity.script.ScriptExecutorActivity",
      "name": "Script with syntax Error",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=365,ly=138,xs=273&457,ys=138&138"},
        "event": "FINISH",
        "id": "T4",
        "to": "A2"
      }]
    },
    {
      "attributes": {
        "WORK_DISPLAY_INFO": "x=520,y=262,w=176,h=65",
        "processname": "com.centurylink.mdw.tests.workflow/MDWTestSubProcess2",
        "processversion": "[0.4,1)",
        "synchronous": "TRUE"
      },
      "id": "A6",
      "implementor": "com.centurylink.mdw.workflow.activity.process.InvokeSubProcessActivity",
      "name": "Invoke Subprocess with Error",
      "transitions": [{
        "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=520,ly=209,xs=520&520,ys=257&162"},
        "event": "FINISH",
        "id": "T5",
        "to": "A2"
      }]
    }
  ],
  "attributes": {
    "ArrowStyle": "ArrowEnd",
    "NodeStyle": "BoxIcon",
    "PROCESS_VISIBILITY": "PUBLIC",
    "WORK_DISPLAY_INFO": "x=50,y=50,w=159,h=27"
  },
  "subprocesses": [{
    "activities": [
      {
        "attributes": {"WORK_DISPLAY_INFO": "x=208,y=419,w=60,h=40"},
        "id": "A7",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessStartActivity",
        "name": "Start",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=303,ly=439,xs=272&335,ys=439&439"},
          "event": "FINISH",
          "id": "T6",
          "to": "A11"
        }]
      },
      {
        "attributes": {
          "DoNotNotifyCaller": "false",
          "WORK_DISPLAY_INFO": "x=508,y=419,w=60,h=40"
        },
        "id": "A10",
        "implementor": "com.centurylink.mdw.workflow.activity.process.ProcessFinishActivity",
        "name": "Stop"
      },
      {
        "attributes": {
          "STATUS_AFTER_EVENT": "Cancelled",
          "TASK_PAGELET": "com.centurylink.mdw.base/AutoFormManualTask.pagelet",
          "TASK_TEMPLATE": "com.centurylink.mdw.tests.workflow/activityExceptionFallout.task",
          "TASK_TEMPLATE_assetVersion": "[0.2,1)",
          "WORK_DISPLAY_INFO": "x=339,y=410,w=100,h=60",
          "Wait for Task": "TRUE"
        },
        "id": "A11",
        "implementor": "com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity",
        "name": "ActivityException Fallout",
        "transitions": [{
          "attributes": {"TRANSITION_DISPLAY_INFO": "type=Elbow,lx=473,ly=439,xs=443&504,ys=439&439"},
          "event": "FINISH",
          "id": "T7",
          "to": "A10"
        }]
      }
    ],
    "attributes": {
      "EMBEDDED_PROCESS_TYPE": "Exception Handler",
      "PROCESS_VISIBILITY": "EMBEDDED",
      "WORK_DISPLAY_INFO": "x=195,y=379,w=386,h=116"
    },
    "id": "P9",
    "name": "Exception Handler"
  }],
  "variables": {
    "exception": {
      "category": "LOCAL",
      "type": "java.lang.Exception"
    },
    "processCase": {
      "category": "INPUT",
      "type": "java.lang.String"
    }
  }
}